# Recruitment & Employee Retention Analytics

## Data Cleaning Notebook

### Objective:
Prepare raw recruitment data for analysis by cleaning,
transforming, and creating analytical tables for:
- Job Listings Analysis
- Recruitment KPIs
- Employee Retention Analysis

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv(r"C:\Users\babus\Data_Spark\Project\Global _market\Deployment\Data\raw\global_job_market_dataset.csv")
df.head()

,job_id,title,industry,company_size,country,city,remote_policy,experience_level,education_required,skills,...,employment_type,posted_date,application_deadline,num_applicants,avg_response_time,offer_extended,offer_accepted,starting_salary,tenure_months,churned_within_1yr
0,35baec88-5aa2-4761-a6d2-5ba2d30dfed3,AI Researcher,Finance,51-200,Afghanistan,Jessicahaven,Remote,Senior,Master's,"Python, TensorFlow, JavaScript, Kubernetes, AW...",...,Contract,07-03-2024,16-04-2024,273,8.2,False,False,NaN,NaN,NaN
1,a7d8057c-9d91-4838-b35f-44132aca03bf,AI Researcher,Education,501-1000,Afghanistan,Jenniferfurt,Remote,Senior,NaN,"Excel, Docker, JavaScript, SQL, TensorFlow, Java",...,Internship,22-10-2023,12-11-2023,298,7.7,True,True,79095.83,23.0,False
2,de2e3824-86c4-4baa-a21d-3b582151ab41,AI Researcher,Finance,51-200,Afghanistan,North Charles,Onsite,Mid,NaN,"Excel, Java, AWS",...,Internship,08-12-2024,04-01-2025,194,6.4,False,False,NaN,NaN,NaN
3,0f82991b-b9be-4709-9bba-b118bb7720d4,AI Researcher,Technology,501-1000,Afghanistan,Benjaminhaven,Hybrid,Entry,Master's,"Pandas, GCP, Docker, Java, JavaScript",...,Full-time,08-07-2025,02-09-2025,499,10.1,False,False,NaN,NaN,NaN
4,84ec642d-b8ed-4c4a-9cf4-17a61c41c726,AI Researcher,Healthcare,501-1000,Afghanistan,Port Daniel,Onsite,Entry,Bachelor's,"Python, Pandas, Java",...,Full-time,04-01-2024,24-02-2024,378,11.4,False,False,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   job_id                250000 non-null  str
 1   title                 250000 non-null  str
 2   industry              250000 non-null  str
 3   company_size          250000 non-null  str
 4   country               250000 non-null  str
 5   city                  250000 non-null  str
 6   remote_policy         250000 non-null  str
 7   experience_level      250000 non-null  str
 8   education_required    187310 non-null  str
 9   skills                250000 non-null  str
 10  tech_stack            250000 non-null  str
 11  employment_type       250000 non-null  str
 12  posted_date           250000 non-null  str
 13  application_deadline  250000 non-null  str
 14  num_applicants        250000 non-null  int64
 15  avg_response_time     250000 non-null  float64
 16  offer_extended        250000 non-null  bool
 17  offer_accepted        250000 non-null  bool
 18  starting_salary       124968 non-null  float64
 19  tenure_months         62426 non-null   float64
 20  churned_within_1yr    62426 non-null   object
dtypes: bool(2), float64(3), int64(1), object(1), str(14)
memory usage: 36.7+ MB

In [4]:
df.describe()

       num_applicants  avg_response_time  starting_salary  tenure_months
count   250000.000000      250000.000000    124968.000000   62426.000000
mean       252.197124           9.999465     84996.418474      11.995034
std        143.525114           3.001986     14992.414599       7.208699
min          5.000000          -3.200000     18015.940000       0.000000
25%        128.000000           8.000000     74862.220000       6.000000
50%        252.000000          10.000000     85049.760000      12.000000
75%        377.000000          12.000000     95089.990000      18.000000
max        500.000000          23.700000    152186.260000      24.000000

In [5]:
df.describe(exclude = 'number')

,job_id,title,industry,company_size,country,city,remote_policy,experience_level,education_required,skills,tech_stack,employment_type,posted_date,application_deadline,offer_extended,offer_accepted,churned_within_1yr
count,250000,250000,250000,250000,250000,250000,250000,250000,187310,250000,250000,250000,250000,250000,250000,250000,62426
unique,250000,10,7,7,243,59003,3,4,3,103725,32330,4,731,784,2,2,2
top,35baec88-5aa2-4761-a6d2-5ba2d30dfed3,Data Scientist,Manufacturing,201-500,Congo,Lake Michael,Onsite,Senior,PhD,"AWS, TensorFlow, Java","React, Spark",Full-time,16-02-2025,19-02-2024,False,False,False
freq,1,25228,35776,35947,2067,225,83439,62893,62573,94,785,62753,395,398,125032,187574,32350

In [6]:
df.shape

(250000, 21)

In [7]:
df.columns

Index(['job_id', 'title', 'industry', 'company_size', 'country', 'city',
       'remote_policy', 'experience_level', 'education_required', 'skills',
       'tech_stack', 'employment_type', 'posted_date', 'application_deadline',
       'num_applicants', 'avg_response_time', 'offer_extended',
       'offer_accepted', 'starting_salary', 'tenure_months',
       'churned_within_1yr'],
      dtype='str')

In [8]:
df.duplicated().sum()

np.int64(0)

## Missing Values Handling 

Identify missing values and understand whether they are:
- Data errors
- Business-related missing values

In [9]:
for col in df:
    print(f"---------{col}----------")
    print(df[col].unique())

---------job_id----------
<StringArray>
['35baec88-5aa2-4761-a6d2-5ba2d30dfed3',
 'a7d8057c-9d91-4838-b35f-44132aca03bf',
 'de2e3824-86c4-4baa-a21d-3b582151ab41',
 '0f82991b-b9be-4709-9bba-b118bb7720d4',
 '84ec642d-b8ed-4c4a-9cf4-17a61c41c726',
 'cd609496-e4c8-481f-99b9-b3eb7dbf0e42',
 '6930b4d1-653a-4480-a865-7c38ab6ab35e',
 'c2086866-7e47-47ca-81f1-c30e36c47608',
 'a893a3be-ab3b-4fc0-b498-e79490d2538d',
 '173d467a-0965-4d28-807a-09d976af5511',
 ...
 '1a4b6a95-9e74-4e81-aa81-5cfa7f2864ce',
 '85bf4a75-d976-44a5-ab4a-e8532f72412a',
 '64a65250-6c54-4a7b-82b5-b652fbd361bc',
 '13bc2adc-f033-48b1-845a-7a32abfe7039',
 'b17dc262-7bf8-4fc0-a5c5-168d67e8dc9d',
 'c9d616d8-efbf-4461-aaf2-72bc841edcb8',
 '389c7b33-6ba8-492f-9956-8dc9d7b96540',
 '7d7869cc-52cc-48e8-8047-d5eef24d0429',
 '031e7dbf-014d-4a10-bafa-c725796731f7',
 'fed1c4fd-f8a2-4fbd-a166-54bd687dbbda']
Length: 250000, dtype: str
---------title----------
<StringArray>
[    'AI Researcher',  'Business Analyst',   'Cloud Architect',
     'Data Engineer',    'Data Scientist',   'DevOps Engineer',
   'Product Manager',       'QA Engineer', 'Software Engineer',
       'UX Designer']
Length: 10, dtype: str
---------industry----------
<StringArray>
[       'Finance',      'Education',     'Technology',     'Healthcare',
         'Retail', 'Transportation',  'Manufacturing']
Length: 7, dtype: str
---------company_size----------
<StringArray>
['51-200', '501-1000', 'Jan-50', '10000+', '1001-5000', '201-500',
 '5001-10000']
Length: 7, dtype: str
---------country----------
<StringArray>
[                                 'Afghanistan',
                                      'Albania',
                                      'Algeria',
                               'American Samoa',
                                      'Andorra',
                                       'Angola',
                                     'Anguilla',
 'Antarctica (the territory South of 60 deg S)',
                          'Antigua and Barbuda',
                                    'Argentina',
 ...
                                      'Uruguay',
                                   'Uzbekistan',
                                      'Vanuatu',
                                    'Venezuela',
                                      'Vietnam',
                            'Wallis and Futuna',
                               'Western Sahara',
                                        'Yemen',
                                       'Zambia',
                                     'Zimbabwe']
Length: 243, dtype: str
---------city----------
<StringArray>
[       'Jessicahaven',        'Jenniferfurt',       'North Charles',
       'Benjaminhaven',         'Port Daniel',             'Amybury',
      'West Jerryport',       'South William',       'Taylorborough',
         'Kennethtown',
 ...
      'South Anneside',         'Wernerhaven',      'Lake Jesusbury',
      'Port Bettyside', 'South Trevorborough',    'North Paigehaven',
          'Lesterbury',     'East Leslieberg', 'West Katherineburgh',
   'South Phillipside']
Length: 59003, dtype: str
---------remote_policy----------
<StringArray>
['Remote', 'Onsite', 'Hybrid']
Length: 3, dtype: str
---------experience_level----------
<StringArray>
['Senior', 'Mid', 'Entry', 'Director']
Length: 4, dtype: str
---------education_required----------
<StringArray>
['Master's', nan, 'Bachelor's', 'PhD']
Length: 4, dtype: str
---------skills----------
<StringArray>
['Python, TensorFlow, JavaScript, Kubernetes, AWS, Docker',
        'Excel, Docker, JavaScript, SQL, TensorFlow, Java',
                                        'Excel, Java, AWS',
                   'Pandas, GCP, Docker, Java, JavaScript',
                                    'Python, Pandas, Java',
                      'Kubernetes, TensorFlow, JavaScript',
             'Docker, Excel, Python, GCP, TensorFlow, SQL',
                    'Python, JavaScript, SQL, Pandas, AWS',
                                     'AWS, Docker, Python',
          'TensorFlow, Pandas, AWS, Docker, Python, Excel',
 ...
        'Java, JavaScript, Excel, AWS, Python, TensorFlow',
            'Java, TensorFlow, Docker, Kubernetes, Pandas',
             'Excel, Python, Java, JavaScript, TensorFlow',
            'Java, Python, Kubernetes, GCP, Pandas, Excel',
                        'GCP, Excel, Python, Java, Pandas',
          'SQL, JavaScript, TensorFlow, Docker, Java, AWS',
       'JavaScript, Java, Docker, GCP, Python, Kubernetes',
               'Python, Java, TensorFlow, AWS, Kubernetes',
          'Java, Pandas, SQL, Kubernetes, AWS, JavaScript',
      'Python, TensorFlow, Kubernetes, Excel, Docker, SQL']
Length: 103725, dtype: str
---------tech_stack----------
<StringArray>
[                     'Node.js, Spring, Spark',
                               'Django, Flask',
                      'React, Node.js, Spring',
                   'Node.js, Airflow, MongoDB',
                  'PostgreSQL, Flask, MongoDB',
     'Spring, Flask, Node.js, Airflow, Django',
     'PostgreSQL, Spark, React, Flask, Spring',
                              'Django, Spring',
         'PostgreSQL, MySQL, MongoDB, Node.js',
                              'Node.js, Spark',
 ...
      'React, Django, Node.js, Flask, Airflow',
 'Node.js, PostgreSQL, Django, Airflow, MySQL',
     'Spring, Flask, MySQL, React, PostgreSQL',
   'Flask, PostgreSQL, React, MongoDB, Spring',
   'Spring, PostgreSQL, Spark, Node.js, MySQL',
      'Spark, MongoDB, React, Airflow, Django',
      'Node.js, Spark, Airflow, Spring, React',
     'MySQL, React, Flask, PostgreSQL, Django',
    'Airflow, Flask, React, PostgreSQL, Spark',
 'React, MongoDB, PostgreSQL, Node.js, Spring']
Length: 32330, dtype: str
---------employment_type----------
<StringArray>
['Contract', 'Internship', 'Full-time', 'Part-time']
Length: 4, dtype: str
---------posted_date----------
<StringArray>
['07-03-2024', '22-10-2023', '08-12-2024', '08-07-2025', '04-01-2024',
 '18-03-2024', '13-05-2025', '11-01-2025', '25-06-2025', '14-06-2025',
 ...
 '18-11-2023', '21-12-2023', '20-09-2023', '04-07-2025', '27-01-2025',
 '06-02-2024', '04-12-2023', '08-08-2024', '17-03-2024', '15-11-2024']
Length: 731, dtype: str
---------application_deadline----------
<StringArray>
['16-04-2024', '12-11-2023', '04-01-2025', '02-09-2025', '24-02-2024',
 '24-04-2024', '04-07-2025', '25-01-2025', '08-08-2025', '03-07-2025',
 ...
 '28-08-2025', '30-07-2023', '23-07-2023', '06-09-2025', '25-07-2023',
 '08-09-2025', '21-07-2023', '22-07-2023', '09-09-2025', '11-09-2025']
Length: 784, dtype: str
---------num_applicants----------
[273 298 194 499 378 484  24 432 256 167 201  39  81 379 214 330 234 203
 215  64 262 101 200 251 263 335 163 467 400 310 213 172 197 156 175 170
 489  35 495 414  32  77 455 248 469 324 260 421 318 364 419 255 131 232
 326 446 373 236 212 168 404 384 487  56  72 104 328 359 490 154  50 223
 115 247 425  26  33 246 140 353 468 437 281  89  90 478 292 297 413 191
 327 220 103  12  71 466 187 394  84  85 340 241  15 366  23 389 411 229
 257 397 174  78 124 114 442 207 311   7 123 271 147 117 355 290 235 144
  53 403 447 276 266 285 127  66  52  36 429  22 343  43 208 250 309 233
 477 145 254 312 275 417  65 306 385  83 346  88 491 279 300 448 198 367
 337 492 274 376 258 444 426 180 325 139 204  92 398 202 225  96   5 228
 341 405 302 192 360 418 164 125 452  97 105 458  25  44 107 294  67 199
 135 182  68 193  55 322 150 482 122 288 334  59  20 449 278 237 470  70
 320 295 352 242  63  91 184 496 252 415   8 181 130 402 277  19 186 261
  37 106 454 280 210 128 433 493 245 265  16 190 119 438 347  28  51  99
 195 118 368 289 451 129 221  30  60 218 407 244 338 350  14 396 435 178
 304  76 391  61 226 434 133 305 409 380 161 383 375 342  31 314 132  69
 162   9 453 358  45 339 134 450  49 284 393 153 436 108  18 183 165 224
 363 372 286 173 406 293  80 189 401 370 149 227 423 374 479 217 497 344
 282  27 356 459 137 390 249  41 301 238  58  79 148 171  17 303 209  74
   6 461 138  93 121 381  40 205 361 211 457 345 443 316 422 410 296 240
 307  95 188 463 239 371 416 475 222  82 472 319 110  48 348 431 196 120
 151 155 362 464 321 113 456 268 486 460  54 387 111 445 323 439 270 427
  47  29 354 473 313 315 408  46 176 169 177 476 430  38 142  94 219 382
 440 158 349 395 351 481 269 386 333 483 126 143 412  11 166 485 157 420
 159 369 365 264  98 231 399 357 206 331  21 329 116 336 185 471 424 267
  86 441 392  73 388 474 152 317 498 308  42 216 291 283 332  34 500 480
  57  75 243 299 488 259 462 100 136 465 112 287  13 377 230 494  10 160
 102 141  87 428 179  62 109 253 146 272]
---------avg_response_time----------
[ 8.2  7.7  6.4 10.1 11.4 10.5  2.9  8.7  9.7  7.1 12.5  8.3 10.3  9.5
 11.5  7.5  5.6  8.5 16.3 12.7 10.7  5.7 15.5 13.4  6.2  6.9 15.6 10.2
 12.6  9.3  8.4 14.3 13.6 11.2  7.6  4.4  9.9 10.9 15.2 12.3  9.6  7.8
 10.4 15.9 13.5 10.  14.6 11.3 12.1  6.7  9.4  7.  11.8 14.5 11.  17.5
  5.5 11.1 16.9  6.6  9.2 12.   4.8 14.4  6.8  6.5 12.2 12.9  5.3 13.
  2.5  8.1  7.4 13.9 13.1  8.9  5.8  2.2 16.4 14.   3.7 18.2 11.6  7.3
  7.9  9.  13.7  6.  12.8  8.6  5.2 17.9 10.8 14.9  3.5 11.7  2.6 10.6
  9.8  4.7 16.2  0.9 14.1  6.3 13.8  8.   8.8  4.9 15.4 14.8 15.1 13.2
 16.7  5.4  1.9 11.9 15.   7.2  3.4  5.  14.7  4.3 16.5 17.2  9.1 19.2
 12.4 14.2  4.6 13.3  5.9 15.8  2.3  4.5  3.   6.1 16.   2.8  1.2 17.
  3.8  3.3  5.1  1.4 17.4 15.7 20.  16.1 18.1  2.7  4.2  1.5  2.1  0.2
  2.   4.1 18.5 17.7 15.3 20.9 -2.  19.1 17.6  1.   3.9  1.1  2.4 19.6
  3.2 16.6 16.8 17.1 -0.1 17.8  0.1  3.1  3.6 17.3 -0.5  4.  18.4 20.4
 18.9  1.7 19.4 19.7  0.5 18.6 18.  20.6  0.8 19.5  1.3  1.6  1.8 21.4
 20.2  0.7 18.7 18.3 19.3 19.  21.  -0.3 19.9 -1.1 -0.8  0.6 18.8  0.
 21.8 -3.2  0.3 -1.2 20.1  0.4 -0.9 20.7 -0.2 -1.  -0.4 19.8 -1.5 20.3
 -1.4 22.6 21.1 21.3 -0.7 21.2 20.8 -1.3 -2.5 23.7 -1.8 20.5 -0.6 -3.1
 -1.6 21.6 -2.2 -2.8]
---------offer_extended----------
[False  True]
---------offer_accepted----------
[False  True]
---------starting_salary----------
[      nan  79095.83  98917.21 ... 102310.8   59966.18  68784.56]
---------tenure_months----------
[nan 23. 18. 10. 11.  9. 13. 14.  4.  3. 22. 12. 20.  7.  8.  2. 24. 15.
  0. 21.  6. 17.  5. 16.  1. 19.]
---------churned_within_1yr----------
[nan False True]

In [10]:
# Replace job_id with numbers starting from 1 to N
df['job_id'] = np.arange(1 , len(df) + 1)

In [11]:
#  clean Jan-50 to 1-50 in company_size
# df['company_size'] = df['company_size'].replace('Jan-50',"1-50",regex=True)
df['company_size'] = df['company_size'].replace('(?i)Jan-50', "1-50", regex=True)

In [12]:
# fixing ~ education_required not null to 'Not-specified'
df['education_required'] = df['education_required'].fillna('Not-specified')

In [13]:
# converting string datatype (application_deadline and posted_date) to date format.
df['application_deadline'] = pd.to_datetime(df['application_deadline'],dayfirst=True,errors='coerce')

In [14]:
df['posted_date'] = pd.to_datetime(df['posted_date'],dayfirst=True,errors='coerce')

In [15]:
# in avg_response_time convarting negative value to absolute value 
# also change the feature name into avg_response_hours
df = df.rename(columns={'avg_response_time':'avg_response_hours'})
df['avg_response_hours'] = df['avg_response_hours'].abs()

In [16]:
# grouping avg_response_time in a 4 group

df['avg_response_hours'] = pd.cut(
    df['avg_response_hours'], 
    bins=[-float('inf'), 6, 12, 18, float('inf')], 
    labels=['0-6', '6-12', '12-18', '18-24']
)

In [17]:
# starting_salary 
df['starting_salary'].isna().mean()* 100   #about 50% datas are missing

np.float64(50.0128)

In [18]:
# create a new feature company type 
company_type_mapping = {
    "1-50": "Startup",
    "51-200": "Scale-up",
    "201-500": "Mid-Market",
    "501-1000": "Enterprise",
    "1001-5000": "Corporation",
    "5001-10000": "MNC",
    "10000+": "MNC",
}
df["company_tier"] = df["company_size"].map(
    company_type_mapping
)

In [19]:
# 
pd.crosstab(
    df['offer_accepted'],
    df['starting_salary'].isna(),
    margins=True
)

starting_salary   False    True     All
offer_accepted
False             62542  125032  187574
True              62426       0   62426
All              124968  125032  250000

Offer Accepted = False → salary missing
Offer Accepted = True → salary present

In [20]:
df[df['offer_accepted'] == True]['starting_salary'].isna().sum()

np.int64(0)

Salary and retention metrics were analyzed only for accepted offers because compensation and tenure information are only available after successful hiring.
so better to keep this feature null and keep it for anaylaze who successfully acepted offer is == True

In [21]:
# tenure_months 
df['tenure_months'].isna().sum()

np.int64(187574)

In [22]:
df['tenure_months'].unique()

array([nan, 23., 18., 10., 11.,  9., 13., 14.,  4.,  3., 22., 12., 20.,
        7.,  8.,  2., 24., 15.,  0., 21.,  6., 17.,  5., 16.,  1., 19.])

In [23]:
has_negative = (df['tenure_months'] < 0 ).any()
print(has_negative)

False

In [24]:
df['tenure_months'] = df['tenure_months'].astype('Int64')

In [25]:
for col in df:
    print(f"---------{col}----------")
    print(df[col].unique())

---------job_id----------
[     1      2      3 ... 249998 249999 250000]
---------title----------
<StringArray>
[    'AI Researcher',  'Business Analyst',   'Cloud Architect',
     'Data Engineer',    'Data Scientist',   'DevOps Engineer',
   'Product Manager',       'QA Engineer', 'Software Engineer',
       'UX Designer']
Length: 10, dtype: str
---------industry----------
<StringArray>
[       'Finance',      'Education',     'Technology',     'Healthcare',
         'Retail', 'Transportation',  'Manufacturing']
Length: 7, dtype: str
---------company_size----------
<StringArray>
['51-200', '501-1000', '1-50', '10000+', '1001-5000', '201-500', '5001-10000']
Length: 7, dtype: str
---------country----------
<StringArray>
[                                 'Afghanistan',
                                      'Albania',
                                      'Algeria',
                               'American Samoa',
                                      'Andorra',
                                       'Angola',
                                     'Anguilla',
 'Antarctica (the territory South of 60 deg S)',
                          'Antigua and Barbuda',
                                    'Argentina',
 ...
                                      'Uruguay',
                                   'Uzbekistan',
                                      'Vanuatu',
                                    'Venezuela',
                                      'Vietnam',
                            'Wallis and Futuna',
                               'Western Sahara',
                                        'Yemen',
                                       'Zambia',
                                     'Zimbabwe']
Length: 243, dtype: str
---------city----------
<StringArray>
[       'Jessicahaven',        'Jenniferfurt',       'North Charles',
       'Benjaminhaven',         'Port Daniel',             'Amybury',
      'West Jerryport',       'South William',       'Taylorborough',
         'Kennethtown',
 ...
      'South Anneside',         'Wernerhaven',      'Lake Jesusbury',
      'Port Bettyside', 'South Trevorborough',    'North Paigehaven',
          'Lesterbury',     'East Leslieberg', 'West Katherineburgh',
   'South Phillipside']
Length: 59003, dtype: str
---------remote_policy----------
<StringArray>
['Remote', 'Onsite', 'Hybrid']
Length: 3, dtype: str
---------experience_level----------
<StringArray>
['Senior', 'Mid', 'Entry', 'Director']
Length: 4, dtype: str
---------education_required----------
<StringArray>
['Master's', 'Not-specified', 'Bachelor's', 'PhD']
Length: 4, dtype: str
---------skills----------
<StringArray>
['Python, TensorFlow, JavaScript, Kubernetes, AWS, Docker',
        'Excel, Docker, JavaScript, SQL, TensorFlow, Java',
                                        'Excel, Java, AWS',
                   'Pandas, GCP, Docker, Java, JavaScript',
                                    'Python, Pandas, Java',
                      'Kubernetes, TensorFlow, JavaScript',
             'Docker, Excel, Python, GCP, TensorFlow, SQL',
                    'Python, JavaScript, SQL, Pandas, AWS',
                                     'AWS, Docker, Python',
          'TensorFlow, Pandas, AWS, Docker, Python, Excel',
 ...
        'Java, JavaScript, Excel, AWS, Python, TensorFlow',
            'Java, TensorFlow, Docker, Kubernetes, Pandas',
             'Excel, Python, Java, JavaScript, TensorFlow',
            'Java, Python, Kubernetes, GCP, Pandas, Excel',
                        'GCP, Excel, Python, Java, Pandas',
          'SQL, JavaScript, TensorFlow, Docker, Java, AWS',
       'JavaScript, Java, Docker, GCP, Python, Kubernetes',
               'Python, Java, TensorFlow, AWS, Kubernetes',
          'Java, Pandas, SQL, Kubernetes, AWS, JavaScript',
      'Python, TensorFlow, Kubernetes, Excel, Docker, SQL']
Length: 103725, dtype: str
---------tech_stack----------
<StringArray>
[                     'Node.js, Spring, Spark',
                               'Django, Flask',
                      'React, Node.js, Spring',
                   'Node.js, Airflow, MongoDB',
                  'PostgreSQL, Flask, MongoDB',
     'Spring, Flask, Node.js, Airflow, Django',
     'PostgreSQL, Spark, React, Flask, Spring',
                              'Django, Spring',
         'PostgreSQL, MySQL, MongoDB, Node.js',
                              'Node.js, Spark',
 ...
      'React, Django, Node.js, Flask, Airflow',
 'Node.js, PostgreSQL, Django, Airflow, MySQL',
     'Spring, Flask, MySQL, React, PostgreSQL',
   'Flask, PostgreSQL, React, MongoDB, Spring',
   'Spring, PostgreSQL, Spark, Node.js, MySQL',
      'Spark, MongoDB, React, Airflow, Django',
      'Node.js, Spark, Airflow, Spring, React',
     'MySQL, React, Flask, PostgreSQL, Django',
    'Airflow, Flask, React, PostgreSQL, Spark',
 'React, MongoDB, PostgreSQL, Node.js, Spring']
Length: 32330, dtype: str
---------employment_type----------
<StringArray>
['Contract', 'Internship', 'Full-time', 'Part-time']
Length: 4, dtype: str
---------posted_date----------
<DatetimeArray>
['2024-03-07 00:00:00', '2023-10-22 00:00:00', '2024-12-08 00:00:00',
 '2025-07-08 00:00:00', '2024-01-04 00:00:00', '2024-03-18 00:00:00',
 '2025-05-13 00:00:00', '2025-01-11 00:00:00', '2025-06-25 00:00:00',
 '2025-06-14 00:00:00',
 ...
 '2023-11-18 00:00:00', '2023-12-21 00:00:00', '2023-09-20 00:00:00',
 '2025-07-04 00:00:00', '2025-01-27 00:00:00', '2024-02-06 00:00:00',
 '2023-12-04 00:00:00', '2024-08-08 00:00:00', '2024-03-17 00:00:00',
 '2024-11-15 00:00:00']
Length: 731, dtype: datetime64[us]
---------application_deadline----------
<DatetimeArray>
['2024-04-16 00:00:00', '2023-11-12 00:00:00', '2025-01-04 00:00:00',
 '2025-09-02 00:00:00', '2024-02-24 00:00:00', '2024-04-24 00:00:00',
 '2025-07-04 00:00:00', '2025-01-25 00:00:00', '2025-08-08 00:00:00',
 '2025-07-03 00:00:00',
 ...
 '2025-08-28 00:00:00', '2023-07-30 00:00:00', '2023-07-23 00:00:00',
 '2025-09-06 00:00:00', '2023-07-25 00:00:00', '2025-09-08 00:00:00',
 '2023-07-21 00:00:00', '2023-07-22 00:00:00', '2025-09-09 00:00:00',
 '2025-09-11 00:00:00']
Length: 784, dtype: datetime64[us]
---------num_applicants----------
[273 298 194 499 378 484  24 432 256 167 201  39  81 379 214 330 234 203
 215  64 262 101 200 251 263 335 163 467 400 310 213 172 197 156 175 170
 489  35 495 414  32  77 455 248 469 324 260 421 318 364 419 255 131 232
 326 446 373 236 212 168 404 384 487  56  72 104 328 359 490 154  50 223
 115 247 425  26  33 246 140 353 468 437 281  89  90 478 292 297 413 191
 327 220 103  12  71 466 187 394  84  85 340 241  15 366  23 389 411 229
 257 397 174  78 124 114 442 207 311   7 123 271 147 117 355 290 235 144
  53 403 447 276 266 285 127  66  52  36 429  22 343  43 208 250 309 233
 477 145 254 312 275 417  65 306 385  83 346  88 491 279 300 448 198 367
 337 492 274 376 258 444 426 180 325 139 204  92 398 202 225  96   5 228
 341 405 302 192 360 418 164 125 452  97 105 458  25  44 107 294  67 199
 135 182  68 193  55 322 150 482 122 288 334  59  20 449 278 237 470  70
 320 295 352 242  63  91 184 496 252 415   8 181 130 402 277  19 186 261
  37 106 454 280 210 128 433 493 245 265  16 190 119 438 347  28  51  99
 195 118 368 289 451 129 221  30  60 218 407 244 338 350  14 396 435 178
 304  76 391  61 226 434 133 305 409 380 161 383 375 342  31 314 132  69
 162   9 453 358  45 339 134 450  49 284 393 153 436 108  18 183 165 224
 363 372 286 173 406 293  80 189 401 370 149 227 423 374 479 217 497 344
 282  27 356 459 137 390 249  41 301 238  58  79 148 171  17 303 209  74
   6 461 138  93 121 381  40 205 361 211 457 345 443 316 422 410 296 240
 307  95 188 463 239 371 416 475 222  82 472 319 110  48 348 431 196 120
 151 155 362 464 321 113 456 268 486 460  54 387 111 445 323 439 270 427
  47  29 354 473 313 315 408  46 176 169 177 476 430  38 142  94 219 382
 440 158 349 395 351 481 269 386 333 483 126 143 412  11 166 485 157 420
 159 369 365 264  98 231 399 357 206 331  21 329 116 336 185 471 424 267
  86 441 392  73 388 474 152 317 498 308  42 216 291 283 332  34 500 480
  57  75 243 299 488 259 462 100 136 465 112 287  13 377 230 494  10 160
 102 141  87 428 179  62 109 253 146 272]
---------avg_response_hours----------
['6-12', '0-6', '12-18', '18-24']
Categories (4, str): ['0-6' < '6-12' < '12-18' < '18-24']
---------offer_extended----------
[False  True]
---------offer_accepted----------
[False  True]
---------starting_salary----------
[      nan  79095.83  98917.21 ... 102310.8   59966.18  68784.56]
---------tenure_months----------
<IntegerArray>
[<NA>,   23,   18,   10,   11,    9,   13,   14,    4,    3,   22,   12,   20,
    7,    8,    2,   24,   15,    0,   21,    6,   17,    5,   16,    1,   19]
Length: 26, dtype: Int64
---------churned_within_1yr----------
[nan False True]
---------company_tier----------
<StringArray>
['Scale-up', 'Enterprise', 'Startup', 'MNC', 'Corporation', 'Mid-Market']
Length: 6, dtype: str

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   job_id                250000 non-null  int64
 1   title                 250000 non-null  str
 2   industry              250000 non-null  str
 3   company_size          250000 non-null  str
 4   country               250000 non-null  str
 5   city                  250000 non-null  str
 6   remote_policy         250000 non-null  str
 7   experience_level      250000 non-null  str
 8   education_required    250000 non-null  str
 9   skills                250000 non-null  str
 10  tech_stack            250000 non-null  str
 11  employment_type       250000 non-null  str
 12  posted_date           250000 non-null  datetime64[us]
 13  application_deadline  250000 non-null  datetime64[us]
 14  num_applicants        250000 non-null  int64
 15  avg_response_hours    250000 non-null  category
 16  offer_extended        250000 non-null  bool
 17  offer_accepted        250000 non-null  bool
 18  starting_salary       124968 non-null  float64
 19  tenure_months         62426 non-null   Int64
 20  churned_within_1yr    62426 non-null   object
 21  company_tier          250000 non-null  str
dtypes: Int64(1), bool(2), category(1), datetime64[us](2), float64(1), int64(2), object(1), str(12)
memory usage: 37.2+ MB

In [27]:
df.head()

,job_id,title,industry,company_size,country,city,remote_policy,experience_level,education_required,skills,...,posted_date,application_deadline,num_applicants,avg_response_hours,offer_extended,offer_accepted,starting_salary,tenure_months,churned_within_1yr,company_tier
0,1,AI Researcher,Finance,51-200,Afghanistan,Jessicahaven,Remote,Senior,Master's,"Python, TensorFlow, JavaScript, Kubernetes, AW...",...,2024-03-07,2024-04-16,273,6-12,False,False,NaN,<NA>,NaN,Scale-up
1,2,AI Researcher,Education,501-1000,Afghanistan,Jenniferfurt,Remote,Senior,Not-specified,"Excel, Docker, JavaScript, SQL, TensorFlow, Java",...,2023-10-22,2023-11-12,298,6-12,True,True,79095.83,23,False,Enterprise
2,3,AI Researcher,Finance,51-200,Afghanistan,North Charles,Onsite,Mid,Not-specified,"Excel, Java, AWS",...,2024-12-08,2025-01-04,194,6-12,False,False,NaN,<NA>,NaN,Scale-up
3,4,AI Researcher,Technology,501-1000,Afghanistan,Benjaminhaven,Hybrid,Entry,Master's,"Pandas, GCP, Docker, Java, JavaScript",...,2025-07-08,2025-09-02,499,6-12,False,False,NaN,<NA>,NaN,Enterprise
4,5,AI Researcher,Healthcare,501-1000,Afghanistan,Port Daniel,Onsite,Entry,Bachelor's,"Python, Pandas, Java",...,2024-01-04,2024-02-24,378,6-12,False,False,NaN,<NA>,NaN,Enterprise

## Create separate analytical tables based on business processes.

In [28]:
job_listings = df[[
    'job_id',
    'title',
    'industry',
    'company_size',
    'company_tier',
    'country',
    'city',
    'remote_policy',
    'experience_level',
    'education_required',
    'skills',
    'tech_stack',
    'employment_type',
    'posted_date',
    'application_deadline'
]]

In [29]:
recruiting_kpis = df[[
    'job_id',
    'num_applicants',
    'avg_response_hours',
    'offer_extended',
    'offer_accepted'
]]

In [30]:
retention_kpis =df[ 
    df['offer_accepted'] == True
    ] [[
    'job_id',
    'starting_salary',
    'tenure_months',
    'churned_within_1yr'
    ]]

In [31]:
job_listings.shape , recruiting_kpis.shape , retention_kpis.shape

((250000, 15), (250000, 5), (62426, 4))

In [32]:
job_listings.isna().sum()

job_id                  0
title                   0
industry                0
company_size            0
company_tier            0
country                 0
city                    0
remote_policy           0
experience_level        0
education_required      0
skills                  0
tech_stack              0
employment_type         0
posted_date             0
application_deadline    0
dtype: int64

In [33]:
recruiting_kpis.isna().sum()

job_id                0
num_applicants        0
avg_response_hours    0
offer_extended        0
offer_accepted        0
dtype: int64

In [34]:
retention_kpis.isna().sum()

job_id                0
starting_salary       0
tenure_months         0
churned_within_1yr    0
dtype: int64

## Save Clean Data

In [35]:
# save retention_kpis
retention_kpis.to_csv(
    r"C:\Users\babus\Data_Spark\Project\Global _market\Deployment\data\processed\retention_kpis.csv",
    index=False
)

# save recruiting_kpis
recruiting_kpis.to_csv(
    r"C:\Users\babus\Data_Spark\Project\Global _market\Deployment\data\processed\recruiting_kpis.csv",
    index=False
)

# save job_listings
job_listings.to_csv(
    r"C:\Users\babus\Data_Spark\Project\Global _market\Deployment\data\processed\job_listings.csv",
    index=False
)

## Cleaning Completed

Created:
- job_listings.csv
- recruiting_kpis.csv
- retention_kpis.csv

Ready for:
- EDA
- SQL Analysis
- Power BI Dashboard